config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'
  resources :answers
  resources :questions

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	include HasGravatar

	belongs_to :question
end

app/models/concerns/has_gravatar.rb
module HasGravatar
	
	def gravatar
			"http://en.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
	end
end	

app/models/question.rb
	
class Question < ActiveRecord::Base
	include HasGravatar

	has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def create
		question = Question.find(params[:answer][:question_id])
		question.answers.create(answer_params)
		session[:current_user_email] = answer_params[:email]
		redirect_to question
	end

	private

	def answer_params
		params.require(:answer).permit(:email, :body)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@questions = Question.order(created_at: :desc).all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
# skip_before_filter  :verify_authenticity_token
	def show
		@question = Question.find(params[:id])
		@answers = @question.answers.order(created_at: :desc).all
	end

	def create
		Question.create(question_params)
		session[:current_user_email] = question_params[:email]
		redirect_to root_path
	end
		
	private 
		def question_params
			params.require(:question).permit(:email, :body)
		end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user_email
		session[:current_user_email]
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-inverse" >
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">History of The Universe</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <div class="navbar-text"><%= current_user_email%></div>
        </li>
        <li><form><a href="#" class="btn btn-success navbar-btn btn-sm" data-toggle="modal" data-target="#new-question-modal">Ask Question</a></form></li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/_new_answer_form.erb
<div class="modal fade" id="new-answer-modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Answer Question</h4>
      </div>
      <%= form_for :answer, url: '/answers', html: { class: 'form-horizontal' } do %>
      <div class="modal-body">
        <div class="form-group">
          <input type="hidden" name="answer[question_id]" value="<%= @question.id %>">
          <label for="inputEmail" class="col-sm-2 control-label">Email</label>
          <div class="col-sm-10">
            <input type="email" name="answer[email]" value="<%= current_user_email %>" class="form-control" id="inputEmail" placeholder="Email" required>
          </div>
        </div>
        <div class="form-group">
          <label for="inputQuestion" class="col-sm-2 control-label">Question</label>
          <div class="col-sm-10">
            <textarea class="form-control" name="answer[body]" id="inputQuestion" placeholder="What would you like to know" required></textarea>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_new_question_form.html.erb
<div class="modal fade" id="new-question-modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Question</h4>
      </div>
      <%= form_for :question, url: '/questions', html: { class: 'form-horizontal' } do %>
      <div class="modal-body">
        <div class="form-group">
          <label for="inputEmail" class="col-sm-2 control-label">Email</label>
          <div class="col-sm-10">
            <input type="email" name="question[email]" value="<%= current_user_email %>" class="form-control" id="inputEmail" placeholder="Email" required>
          </div>
        </div>
        <div class="form-group">
          <label for="inputQuestion" class="col-sm-2 control-label">Question</label>
          <div class="col-sm-10">
            <textarea class="form-control" name="question[body]" id="inputQuestion" placeholder="What would you like to know" required></textarea>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="well">
  <h4>The Universe is the totality of everything that exists, has existed, or ever will exist.</h4>
  <p>This Q&amp;A site is dedicated to questions about the history of the Universe</p>
</div>


<div class="container">
  <% @questions.each do |q| %>
  <div class="box">
    <div class="media click-media" data-target="<%= question_path(q) %>">
      <div class="media-left">
        <a href="#">
          <img class="media-object" src="<%= q.gravatar %>">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= q.email %> asked:</h4>
        <div class="time hidden-xs"><%= time_ago_in_words q.created_at %> ago</div>
        <div><%= truncate q.body, length: 300 %></div>
        <div><a href="<%= question_path(q) %>" class="btn btn-success btn-xs btn-view-answer hidden-xs">View Answers</a></div>
      </div>
    </div>
  </div>
  <% end %>
  
  <% if @questions.empty? %>
  <div class="alert alert-info">
    There is no question asked. Please be the first to ask YAY!!
  </div>
  
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Ask the Universe</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'home/navbar' %>	
	<%= yield %>
	<%= render 'home/new_question_form' %>
	
</body>
</html>

app/views/questions/show.html.erb
<div class="container">
  <div class="lead well">

    
    <div class="media">
      <div class="media-left">
        <a href="#">
          <img class="media-object" src="<%= @question.gravatar %>">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= @question.email %> asked:</h4>
        <%= @question.body %>
      </div>
    </div>
  </div>
 

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">

      <div>
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#new-answer-modal">Submit new answer</button>
      </div>
      
      <%= render 'home/new_answer_form' %>

      <% @answers.each do |answer|%>
      <div class="media">
        <div class="media-left">
          <a href="#"><img class="media-object" src="<%= @question.gravatar %>" alt=""></a>
        </div>
        
        
        <div class="media-body">
          <h4 class="media-heading"><%= answer.email %> answered: </h4>
          <div><%= time_ago_in_words answer.created_at %></div>
          <%= answer.body %>
        </div>
      </div>
      <% end %>

      <% if @answers.empty? %>
      <div class="alert alert-info">
        Please be first to answer.
      </div>
      <% end %>

    </div>
  </div>
</div>